FROM node:26.8.1-alpine AS ui-builder

RUN apk add --no-cache git \
	&& corepack enable

WORKDIR /app

RUN git clone --depth 1 https://github.com/siroosab/frequi.git . \
	&& pnpm install --frozen-lockfile \
	&& pnpm run build

FROM freqtradeorg/freqtrade:stable

COPY --from=ui-builder /app/dist/ /freqtrade/freqtrade/rpc/api_server/ui/installed/
RUN printf 'siroosab/frequi-main\n' > /freqtrade/freqtrade/rpc/api_server/ui/installed/.uiversion

